version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: cssnano
    versions:
    - 4.1.11
    - 5.0.0
    - 5.0.1
  - dependency-name: postcss-nested
    versions:
    - 5.0.4
